## Load in NumPy

In [1]:
# !pip install numpy 
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

In [10]:
# Return Index of Max value
a.argmax()

2

In [11]:
# Return Index of Min value
a.argmin()

0

### Way of creating array

In [12]:
# through list
my_list = [1,2,3,4,5]
arr1 = np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [13]:
# through arange()
arr2 = np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [14]:
# through linspace()
arr3 = np.linspace(1,50)
arr3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [15]:
# through random.rand()
arr4 = np.random.rand(1,10)
arr4

array([[0.05343318, 0.76411724, 0.63803287, 0.13103373, 0.15065483,
        0.18555403, 0.06104802, 0.29411364, 0.37224497, 0.57832816]])

In [16]:
# through random.randint()
arr4 = np.random.randint(1,100,10)
arr4

array([73,  5,  6, 83, 32, 44, 74, 21, 74, 43])

In [17]:
# convert 1-D into Multi-Dimension
arr5 = np.random.randint(1,100,20).reshape(5,4)
arr5

array([[ 2, 74, 25, 91],
       [59, 70, 65, 67],
       [78, 43, 39, 93],
       [10,  6, 77, 90],
       [70,  7, 73, 60]])

In [18]:
# convert Multi-Dimension into 1-D
# its will not change original array
arr5.ravel()

array([ 2, 74, 25, 91, 59, 70, 65, 67, 78, 43, 39, 93, 10,  6, 77, 90, 70,
        7, 73, 60])

In [19]:
# copy array 
new_arr = arr5.copy()
new_arr

array([[ 2, 74, 25, 91],
       [59, 70, 65, 67],
       [78, 43, 39, 93],
       [10,  6, 77, 90],
       [70,  7, 73, 60]])

### Accessing/Changing specific elements, rows, columns, etc

In [20]:
arr4[:]

array([73,  5,  6, 83, 32, 44, 74, 21, 74, 43])

In [21]:
arr4[1]

5

In [22]:
arr4[:3]

array([73,  5,  6])

In [23]:
arr4[2:]

array([ 6, 83, 32, 44, 74, 21, 74, 43])

In [24]:
arr4[2:4] = 99
arr4

array([73,  5, 99, 99, 32, 44, 74, 21, 74, 43])

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get all element
a[:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
# Get a specific element [r, c]
a[1, 5]

13

In [28]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [30]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [31]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [32]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
b.ndim

3

In [35]:
# replace 
b[:,1:,1] = 8

In [36]:
b

array([[[1, 2],
        [3, 8]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [37]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [39]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.94702292, 0.55772338],
       [0.04129309, 0.21915715],
       [0.86458545, 0.80968685],
       [0.07881638, 0.81268804]])

In [42]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -3,  3],
       [ 0, -3,  1],
       [-3, -4,  3]])

In [43]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [46]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [47]:
y = np.array([5,2,8,6])
y

array([5, 2, 8, 6])

In [48]:
x + 2

array([3, 4, 5, 6])

In [49]:
y - 2

array([3, 0, 6, 4])

In [50]:
x * 2

array([2, 4, 6, 8])

In [51]:
x / 2

array([0.5, 1. , 1.5, 2. ])

In [52]:
x ** 2

array([ 1,  4,  9, 16])

In [53]:
# Adding to Matrix
x + y

array([ 6,  4, 11, 10])

In [54]:
# Subtract to Matrix
x - y

array([-4,  0, -5, -2])

In [55]:
# Multiply to Matrix
x * y

array([ 5,  4, 24, 24])

In [56]:
# Divide to Matrix
x / y

array([0.2       , 1.        , 0.375     , 0.66666667])

In [57]:
# Take the sin
np.sin(a)


array([[ 0.84147098,  0.90929743,  0.84147098, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.90929743, -0.99999021, -0.53657292,
         0.91294525,  0.99060736]])

In [58]:
# Take the cos
np.cos(a)

array([[ 0.54030231, -0.41614684,  0.54030231, -0.65364362,  0.28366219,
         0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.41614684,  0.0044257 ,  0.84385396,
         0.40808206,  0.13673722]])

In [59]:
# Take the tan
np.tan(a)

array([[   1.55740772,   -2.18503986,    1.55740772,    1.15782128,
          -3.38051501,   -0.29100619,    0.87144798],
       [  -6.79971146,   -0.45231566,   -2.18503986, -225.95084645,
          -0.63585993,    2.23716094,    7.24460662]])

In [60]:
# Take the exp
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.71828183e+00, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 5.98741417e+04,
        1.62754791e+05, 4.85165195e+08, 1.20260428e+06]])

In [61]:
# Take the log
np.log(a)

array([[0.        , 0.69314718, 0.        , 1.38629436, 1.60943791,
        1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 0.69314718, 2.39789527, 2.48490665,
        2.99573227, 2.63905733]])

In [62]:
# Take the sqrt root
np.sqrt(a)

array([[1.        , 1.41421356, 1.        , 2.        , 2.23606798,
        2.44948974, 2.64575131],
       [2.82842712, 3.        , 1.41421356, 3.31662479, 3.46410162,
        4.47213595, 3.74165739]])

In [63]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [64]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [66]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [67]:
# any other number full_like
np.full_like(b, 99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [68]:
# Find the determinant
c = np.eye(3)
np.linalg.det(c)

1.0

In [69]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [70]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [71]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stats)

1

In [73]:
np.max(stats, axis=1)

array([3, 6])

In [74]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [75]:
np.sum(stats, axis=1)

array([ 6, 15])

In [76]:
np.sum(stats)

21

In [77]:
# Finding standard deviation
# nanstd()
np.std(stats, axis=1)

array([0.81649658, 0.81649658])

In [78]:
# Calculating mean
np.mean(stats)

3.5

In [79]:
# nanmean(a)
np.mean(stats, axis=0)

array([2.5, 3.5, 4.5])

In [80]:
# Calculating average
np.average(stats)

3.5

In [81]:
# Calculating Median
# nanmedian(a)
np.median(stats)

3.5

In [82]:
# variance
# nanvar
np.var(a, axis=0)

array([0., 0., 0.])

In [83]:
#Computing the mean in float64 is more accurate
np.mean(stats, dtype=np.float64)

3.5

### Reorganizing Arrays

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
after = before.reshape((2,4))
after

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [88]:
after

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
result = np.hsplit(after,2)
result[0]

array([[1, 2],
       [5, 6]])

In [90]:
result[1]

array([[3, 4],
       [7, 8]])

In [91]:
result = np.vsplit(after,2)
result[0]

array([[1, 2, 3, 4]])

In [92]:
result[1]

array([[5, 6, 7, 8]])

### Miscellaneous
##### Load Data from File

In [93]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1   3  31  61  16  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  92  12  83 766  95   4  55   6   4   3   7   9   6   7   0  11  25]
 [  1  92  33  11  99  11   2   1  78   0   1   2   9   8   7   1  96  78]]


##### Boolean Masking and Advanced Indexing

In [94]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [95]:
tmp_data = filedata > 5
tmp_data

array([[False, False,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False,  True,  True,
        False, False,  True,  True,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False,  True,  True,  True, False,  True,  True]])

In [96]:
filedata[tmp_data]

array([ 31,  61,  16,  75,  34,   6,   7,   8,  92,  12,  83, 766,  95,
        55,   6,   7,   9,   6,   7,  11,  25,  92,  33,  11,  99,  11,
        78,   9,   8,   7,  96,  78], dtype=int32)

In [97]:
# print row element

for row in a:
    print(row)

[1. 1. 1.]
[1. 1. 1.]


In [98]:
# print column element

for cell in a.flat:
    print(cell)

1.0
1.0
1.0
1.0
1.0
1.0


In [99]:
for cell in a.flatten():
    print(cell)

1.0
1.0
1.0
1.0
1.0
1.0


In [100]:
for x in np.nditer(x , order= 'C'):
    print(x)

1
2
3
4


In [101]:
for x in np.nditer(y , order= 'F'):
    print(x)

5
2
8
6
